package com.odd.sportal.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.odd.sportal.model.BetForecastsModel;
import com.odd.sportal.model.EventModel;
import com.odd.sportal.model.GameModel;

import com.odd.sportal.greendao.BetForecastsModelDao;
import com.odd.sportal.greendao.EventModelDao;
import com.odd.sportal.greendao.GameModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig betForecastsModelDaoConfig;
    private final DaoConfig eventModelDaoConfig;
    private final DaoConfig gameModelDaoConfig;

    private final BetForecastsModelDao betForecastsModelDao;
    private final EventModelDao eventModelDao;
    private final GameModelDao gameModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        betForecastsModelDaoConfig = daoConfigMap.get(BetForecastsModelDao.class).clone();
        betForecastsModelDaoConfig.initIdentityScope(type);

        eventModelDaoConfig = daoConfigMap.get(EventModelDao.class).clone();
        eventModelDaoConfig.initIdentityScope(type);

        gameModelDaoConfig = daoConfigMap.get(GameModelDao.class).clone();
        gameModelDaoConfig.initIdentityScope(type);

        betForecastsModelDao = new BetForecastsModelDao(betForecastsModelDaoConfig, this);
        eventModelDao = new EventModelDao(eventModelDaoConfig, this);
        gameModelDao = new GameModelDao(gameModelDaoConfig, this);

        registerDao(BetForecastsModel.class, betForecastsModelDao);
        registerDao(EventModel.class, eventModelDao);
        registerDao(GameModel.class, gameModelDao);
    }
    
    public void clear() {
        betForecastsModelDaoConfig.clearIdentityScope();
        eventModelDaoConfig.clearIdentityScope();
        gameModelDaoConfig.clearIdentityScope();
    }

    public BetForecastsModelDao getBetForecastsModelDao() {
        return betForecastsModelDao;
    }

    public EventModelDao getEventModelDao() {
        return eventModelDao;
    }

    public GameModelDao getGameModelDao() {
        return gameModelDao;
    }

}
