package com.szfp.scan.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.szfp.scan.bean.ShopModel;
import com.szfp.scan.bean.TradingOrderModel;
import com.szfp.scan.bean.TradingShopModel;
import com.szfp.scan.bean.ManagerModel;

import com.szfp.scan.greendao.ShopModelDao;
import com.szfp.scan.greendao.TradingOrderModelDao;
import com.szfp.scan.greendao.TradingShopModelDao;
import com.szfp.scan.greendao.ManagerModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopModelDaoConfig;
    private final DaoConfig tradingOrderModelDaoConfig;
    private final DaoConfig tradingShopModelDaoConfig;
    private final DaoConfig managerModelDaoConfig;

    private final ShopModelDao shopModelDao;
    private final TradingOrderModelDao tradingOrderModelDao;
    private final TradingShopModelDao tradingShopModelDao;
    private final ManagerModelDao managerModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopModelDaoConfig = daoConfigMap.get(ShopModelDao.class).clone();
        shopModelDaoConfig.initIdentityScope(type);

        tradingOrderModelDaoConfig = daoConfigMap.get(TradingOrderModelDao.class).clone();
        tradingOrderModelDaoConfig.initIdentityScope(type);

        tradingShopModelDaoConfig = daoConfigMap.get(TradingShopModelDao.class).clone();
        tradingShopModelDaoConfig.initIdentityScope(type);

        managerModelDaoConfig = daoConfigMap.get(ManagerModelDao.class).clone();
        managerModelDaoConfig.initIdentityScope(type);

        shopModelDao = new ShopModelDao(shopModelDaoConfig, this);
        tradingOrderModelDao = new TradingOrderModelDao(tradingOrderModelDaoConfig, this);
        tradingShopModelDao = new TradingShopModelDao(tradingShopModelDaoConfig, this);
        managerModelDao = new ManagerModelDao(managerModelDaoConfig, this);

        registerDao(ShopModel.class, shopModelDao);
        registerDao(TradingOrderModel.class, tradingOrderModelDao);
        registerDao(TradingShopModel.class, tradingShopModelDao);
        registerDao(ManagerModel.class, managerModelDao);
    }
    
    public void clear() {
        shopModelDaoConfig.clearIdentityScope();
        tradingOrderModelDaoConfig.clearIdentityScope();
        tradingShopModelDaoConfig.clearIdentityScope();
        managerModelDaoConfig.clearIdentityScope();
    }

    public ShopModelDao getShopModelDao() {
        return shopModelDao;
    }

    public TradingOrderModelDao getTradingOrderModelDao() {
        return tradingOrderModelDao;
    }

    public TradingShopModelDao getTradingShopModelDao() {
        return tradingShopModelDao;
    }

    public ManagerModelDao getManagerModelDao() {
        return managerModelDao;
    }

}
