package com.szfp.scan.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.szfp.scan.bean.ShopModel;

import com.szfp.scan.greendao.ShopModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopModelDaoConfig;

    private final ShopModelDao shopModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopModelDaoConfig = daoConfigMap.get(ShopModelDao.class).clone();
        shopModelDaoConfig.initIdentityScope(type);

        shopModelDao = new ShopModelDao(shopModelDaoConfig, this);

        registerDao(ShopModel.class, shopModelDao);
    }
    
    public void clear() {
        shopModelDaoConfig.clearIdentityScope();
    }

    public ShopModelDao getShopModelDao() {
        return shopModelDao;
    }

}
