package com.szfp.scan.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.szfp.scan.bean.TradingShopModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRADING_SHOP_MODEL".
*/
public class TradingShopModelDao extends AbstractDao<TradingShopModel, Long> {

    public static final String TABLENAME = "TRADING_SHOP_MODEL";

    /**
     * Properties of entity TradingShopModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Tid = new Property(0, Long.class, "tid", true, "_id");
        public final static Property Sn = new Property(1, String.class, "sn", false, "SN");
        public final static Property SellNum = new Property(2, int.class, "sellNum", false, "SELL_NUM");
        public final static Property Id = new Property(3, Long.class, "id", false, "ID");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property ItemNo = new Property(5, String.class, "itemNo", false, "ITEM_NO");
        public final static Property Num = new Property(6, int.class, "num", false, "NUM");
        public final static Property Price = new Property(7, double.class, "price", false, "PRICE");
    }


    public TradingShopModelDao(DaoConfig config) {
        super(config);
    }
    
    public TradingShopModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRADING_SHOP_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: tid
                "\"SN\" TEXT," + // 1: sn
                "\"SELL_NUM\" INTEGER NOT NULL ," + // 2: sellNum
                "\"ID\" INTEGER," + // 3: id
                "\"NAME\" TEXT," + // 4: name
                "\"ITEM_NO\" TEXT," + // 5: itemNo
                "\"NUM\" INTEGER NOT NULL ," + // 6: num
                "\"PRICE\" REAL NOT NULL );"); // 7: price
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRADING_SHOP_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TradingShopModel entity) {
        stmt.clearBindings();
 
        Long tid = entity.getTid();
        if (tid != null) {
            stmt.bindLong(1, tid);
        }
 
        String sn = entity.getSn();
        if (sn != null) {
            stmt.bindString(2, sn);
        }
        stmt.bindLong(3, entity.getSellNum());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(4, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String itemNo = entity.getItemNo();
        if (itemNo != null) {
            stmt.bindString(6, itemNo);
        }
        stmt.bindLong(7, entity.getNum());
        stmt.bindDouble(8, entity.getPrice());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TradingShopModel entity) {
        stmt.clearBindings();
 
        Long tid = entity.getTid();
        if (tid != null) {
            stmt.bindLong(1, tid);
        }
 
        String sn = entity.getSn();
        if (sn != null) {
            stmt.bindString(2, sn);
        }
        stmt.bindLong(3, entity.getSellNum());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(4, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String itemNo = entity.getItemNo();
        if (itemNo != null) {
            stmt.bindString(6, itemNo);
        }
        stmt.bindLong(7, entity.getNum());
        stmt.bindDouble(8, entity.getPrice());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TradingShopModel readEntity(Cursor cursor, int offset) {
        TradingShopModel entity = new TradingShopModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // tid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sn
            cursor.getInt(offset + 2), // sellNum
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // itemNo
            cursor.getInt(offset + 6), // num
            cursor.getDouble(offset + 7) // price
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TradingShopModel entity, int offset) {
        entity.setTid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSn(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSellNum(cursor.getInt(offset + 2));
        entity.setId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setItemNo(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setNum(cursor.getInt(offset + 6));
        entity.setPrice(cursor.getDouble(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TradingShopModel entity, long rowId) {
        entity.setTid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TradingShopModel entity) {
        if(entity != null) {
            return entity.getTid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TradingShopModel entity) {
        return entity.getTid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
