package com.szfp.scan.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.szfp.scan.bean.TradingOrderModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRADING_ORDER_MODEL".
*/
public class TradingOrderModelDao extends AbstractDao<TradingOrderModel, Long> {

    public static final String TABLENAME = "TRADING_ORDER_MODEL";

    /**
     * Properties of entity TradingOrderModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sn = new Property(1, String.class, "sn", false, "SN");
        public final static Property TotalAmoumt = new Property(2, double.class, "totalAmoumt", false, "TOTAL_AMOUMT");
        public final static Property TotalNum = new Property(3, int.class, "totalNum", false, "TOTAL_NUM");
        public final static Property Opterator = new Property(4, String.class, "opterator", false, "OPTERATOR");
        public final static Property CreateTime = new Property(5, java.util.Date.class, "createTime", false, "CREATE_TIME");
    }


    public TradingOrderModelDao(DaoConfig config) {
        super(config);
    }
    
    public TradingOrderModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRADING_ORDER_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SN\" TEXT," + // 1: sn
                "\"TOTAL_AMOUMT\" REAL NOT NULL ," + // 2: totalAmoumt
                "\"TOTAL_NUM\" INTEGER NOT NULL ," + // 3: totalNum
                "\"OPTERATOR\" TEXT," + // 4: opterator
                "\"CREATE_TIME\" INTEGER);"); // 5: createTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRADING_ORDER_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TradingOrderModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sn = entity.getSn();
        if (sn != null) {
            stmt.bindString(2, sn);
        }
        stmt.bindDouble(3, entity.getTotalAmoumt());
        stmt.bindLong(4, entity.getTotalNum());
 
        String opterator = entity.getOpterator();
        if (opterator != null) {
            stmt.bindString(5, opterator);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(6, createTime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TradingOrderModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sn = entity.getSn();
        if (sn != null) {
            stmt.bindString(2, sn);
        }
        stmt.bindDouble(3, entity.getTotalAmoumt());
        stmt.bindLong(4, entity.getTotalNum());
 
        String opterator = entity.getOpterator();
        if (opterator != null) {
            stmt.bindString(5, opterator);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(6, createTime.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TradingOrderModel readEntity(Cursor cursor, int offset) {
        TradingOrderModel entity = new TradingOrderModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sn
            cursor.getDouble(offset + 2), // totalAmoumt
            cursor.getInt(offset + 3), // totalNum
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // opterator
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)) // createTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TradingOrderModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSn(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTotalAmoumt(cursor.getDouble(offset + 2));
        entity.setTotalNum(cursor.getInt(offset + 3));
        entity.setOpterator(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCreateTime(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TradingOrderModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TradingOrderModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TradingOrderModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
